//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static Infraestructure.Models.Metadata;

    [MetadataType(typeof(MovimientosMetadata))]
    public partial class Movimientos
    {
        public int Id { get; set; }
        public string Comentario { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Creado { get; set; }
        public int Id_Producto { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_TipoMovimiento { get; set; }
        public double Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
